/**
 * Morocco Trade OS — Deal Negotiation Mock Data
 */

import type { TradeDeal } from '@/types/trade';

export const MOCK_DEALS: TradeDeal[] = [
    {
        id: 'deal-001',
        dealNumber: 'DEAL-001',
        title: 'Argan Oil Supply Contract Q2–Q3 2026',
        status: 'negotiating',
        createdAt: '2026-02-15T10:00:00Z',
        updatedAt: '2026-03-07T17:30:00Z',
        supplierId: 'sup-001',
        supplierName: 'Sahara Gold Cooperative',
        supplierCity: 'Agadir',
        buyerCompany: 'OUROZ Dubai',
        productName: 'Virgin Argan Oil (Cosmetic)',
        category: 'Argan Oil & Derivatives',
        quantity: 1500,
        quantityUnit: 'liters',
        currentTerms: {
            unitPrice: 43.00,
            currency: 'USD',
            quantity: 1500,
            incoterm: 'CIF',
            paymentTerms: '30% advance, 70% on B/L',
            leadTimeDays: 14,
            shippingMethod: 'Sea — Casablanca to Jebel Ali',
            timestamp: '2026-03-07T17:30:00Z',
        },
        termHistory: [
            {
                unitPrice: 46.00,
                currency: 'USD',
                quantity: 1000,
                incoterm: 'CIF',
                paymentTerms: '50% advance, 50% on delivery',
                leadTimeDays: 14,
                shippingMethod: 'Sea',
                timestamp: '2026-02-15T10:00:00Z',
            },
            {
                unitPrice: 44.50,
                currency: 'USD',
                quantity: 1200,
                incoterm: 'CIF',
                paymentTerms: '40% advance, 60% on B/L',
                leadTimeDays: 14,
                shippingMethod: 'Sea',
                timestamp: '2026-02-28T14:00:00Z',
            },
        ],
        messages: [
            {
                id: 'msg-1',
                senderId: 'buyer',
                senderName: 'OUROZ Dubai',
                senderType: 'buyer',
                content: 'We\'d like to discuss a Q2-Q3 supply agreement for cosmetic-grade argan oil. Our initial requirement is 1,000L with potential to increase.',
                timestamp: '2026-02-15T10:00:00Z',
            },
            {
                id: 'msg-2',
                senderId: 'sup-001',
                senderName: 'Fatima El Amrani',
                senderType: 'supplier',
                content: 'Thank you for your interest. We can offer cosmetic-grade argan oil at $46/L CIF Jebel Ali. USDA Organic and Ecocert certified. Lead time 14 days.',
                timestamp: '2026-02-16T09:00:00Z',
            },
            {
                id: 'msg-3',
                senderId: 'ai',
                senderName: 'AI Advisor',
                senderType: 'ai',
                content: 'Market analysis: Current wholesale argan oil prices in Souss-Massa average $44/L. With the recent price drop, you have room to negotiate. Suggest counter-offer at $42/L for a larger volume commitment.',
                timestamp: '2026-02-16T09:05:00Z',
            },
            {
                id: 'msg-4',
                senderId: 'buyer',
                senderName: 'OUROZ Dubai',
                senderType: 'buyer',
                content: 'We appreciate the offer. Given current market conditions, could you consider $42/L if we increase the order to 1,200L? We\'d also prefer 30/70 payment terms.',
                timestamp: '2026-02-20T11:00:00Z',
            },
            {
                id: 'msg-5',
                senderId: 'sup-001',
                senderName: 'Fatima El Amrani',
                senderType: 'supplier',
                content: 'For 1,200L we can offer $44.50/L with 40/60 terms. Our organic certification costs are factored into this price.',
                timestamp: '2026-02-28T14:00:00Z',
            },
            {
                id: 'msg-6',
                senderId: 'buyer',
                senderName: 'OUROZ Dubai',
                senderType: 'buyer',
                content: 'If we commit to 1,500L across Q2-Q3, could you do $43/L? We can agree to 30/70 on B/L terms.',
                timestamp: '2026-03-05T16:00:00Z',
            },
            {
                id: 'msg-7',
                senderId: 'sup-001',
                senderName: 'Fatima El Amrani',
                senderType: 'supplier',
                content: '$43/L for 1,500L is very close to our floor. Let me discuss with the cooperative board and get back to you by Monday.',
                timestamp: '2026-03-07T17:30:00Z',
            },
        ],
        aiStrategyNotes: [
            'Supplier is near their floor price. $43/L for 1,500L is 7% below initial offer — good progress.',
            'Sahara Gold has a 89% repeat buyer rate — they value long-term relationships. Emphasize partnership potential.',
            'Consider offering to feature them as a "Verified Partner" on OUROZ as additional value.',
        ],
        aiRecommendedPrice: 42.50,
        aiConfidence: 72,
        milestones: [
            { label: 'Initial Contact', date: '2026-02-15', completed: true },
            { label: 'First Offer', date: '2026-02-16', completed: true },
            { label: 'Counter-Offer', date: '2026-02-20', completed: true },
            { label: 'Revised Terms', date: '2026-03-05', completed: true },
            { label: 'Final Agreement', date: '2026-03-12', completed: false },
            { label: 'Contract Signed', date: '2026-03-15', completed: false },
        ],
        rfqId: 'rfq-001',
    },
    {
        id: 'deal-002',
        dealNumber: 'DEAL-002',
        title: 'Zellige Tiles — Dubai Luxury Hotel Project',
        status: 'terms_agreed',
        createdAt: '2026-01-20T08:00:00Z',
        updatedAt: '2026-03-06T10:00:00Z',
        supplierId: 'sup-005',
        supplierName: 'Fez Artisan Zellige Co.',
        supplierCity: 'Fes',
        buyerCompany: 'OUROZ Dubai',
        productName: 'Handcut Zellige Tiles',
        category: 'Ceramics & Zellige',
        quantity: 15000,
        quantityUnit: 'pieces',
        currentTerms: {
            unitPrice: 2.45,
            currency: 'USD',
            quantity: 15000,
            incoterm: 'DAP',
            paymentTerms: '20% advance, 30% mid-production, 50% on delivery',
            leadTimeDays: 42,
            shippingMethod: 'Sea — Tanger Med to Jebel Ali',
            specialConditions: 'Custom color palette approval required before production begins. Sample batch of 100 tiles to be approved first.',
            timestamp: '2026-03-06T10:00:00Z',
        },
        termHistory: [],
        messages: [
            {
                id: 'msg-10',
                senderId: 'buyer',
                senderName: 'OUROZ Dubai',
                senderType: 'buyer',
                content: 'We have a luxury hotel project requiring 15,000 handcut zellige tiles in a custom color palette. Can you accommodate?',
                timestamp: '2026-01-20T08:00:00Z',
            },
            {
                id: 'msg-11',
                senderId: 'sup-005',
                senderName: 'Moulay Ahmed Fassi',
                senderType: 'supplier',
                content: 'Absolutely. We have extensive experience with hotel projects — Four Seasons Marrakech, Aman Tokyo, etc. For 15,000 tiles with custom colors, we offer $2.45/piece DAP Dubai.',
                timestamp: '2026-01-22T09:30:00Z',
            },
            {
                id: 'msg-12',
                senderId: 'system',
                senderName: 'System',
                senderType: 'system',
                content: 'Terms agreed by both parties on March 6, 2026. Contract draft being prepared.',
                timestamp: '2026-03-06T10:00:00Z',
            },
        ],
        aiStrategyNotes: [
            '$2.45/piece for 15K tiles is excellent — 12.5% below market average for artisan zellige.',
            'This supplier has UNESCO heritage partnership — strong selling point for luxury hotel buyer.',
        ],
        aiRecommendedPrice: 2.40,
        aiConfidence: 65,
        milestones: [
            { label: 'Initial Contact', date: '2026-01-20', completed: true },
            { label: 'Quote Received', date: '2026-01-22', completed: true },
            { label: 'Sample Approved', date: '2026-02-15', completed: true },
            { label: 'Terms Agreed', date: '2026-03-06', completed: true },
            { label: 'Contract Sent', date: '2026-03-10', completed: false },
            { label: 'Production Start', date: '2026-03-20', completed: false },
        ],
        rfqId: 'rfq-002',
    },
    {
        id: 'deal-003',
        dealNumber: 'DEAL-003',
        title: 'Organic EVOO — Annual Supply Agreement',
        status: 'exploring',
        createdAt: '2026-03-01T14:00:00Z',
        updatedAt: '2026-03-03T09:00:00Z',
        supplierId: 'sup-008',
        supplierName: 'Meknes Olive Estates',
        supplierCity: 'Meknes',
        buyerCompany: 'OUROZ Dubai',
        productName: 'Extra Virgin Olive Oil',
        category: 'Olive Oil & Table Olives',
        quantity: 5000,
        quantityUnit: 'liters',
        currentTerms: {
            unitPrice: 8.50,
            currency: 'USD',
            quantity: 5000,
            incoterm: 'CIF',
            paymentTerms: 'TBD',
            leadTimeDays: 18,
            shippingMethod: 'Sea',
            timestamp: '2026-03-03T09:00:00Z',
        },
        termHistory: [],
        messages: [
            {
                id: 'msg-20',
                senderId: 'buyer',
                senderName: 'OUROZ Dubai',
                senderType: 'buyer',
                content: 'We\'re interested in an annual EVOO supply agreement. Current consumption is 5,000L/year across our retail and wholesale channels.',
                timestamp: '2026-03-01T14:00:00Z',
            },
            {
                id: 'msg-21',
                senderId: 'sup-008',
                senderName: 'Omar El Fassi',
                senderType: 'supplier',
                content: 'Thank you for reaching out. We produce EU Organic certified EVOO from our Meknes estates. For 5,000L annual, we can offer $8.50/L CIF. Happy to send samples.',
                timestamp: '2026-03-03T09:00:00Z',
            },
        ],
        aiStrategyNotes: [
            'EVOO market prices are falling — current Moroccan average is $8.50/L. Wait for further decline before committing.',
            'Meknes Olive Estates has HACCP and EU Organic — premium quality at competitive pricing.',
        ],
        aiRecommendedPrice: 7.80,
        aiConfidence: 58,
        milestones: [
            { label: 'Initial Contact', date: '2026-03-01', completed: true },
            { label: 'First Response', date: '2026-03-03', completed: true },
            { label: 'Sample Request', date: '2026-03-10', completed: false },
            { label: 'Price Negotiation', date: '2026-03-15', completed: false },
        ],
    },
];
