/**
 * Morocco Trade OS — RFQ Mock Data
 */

import type { TradeRFQ } from '@/types/trade';

export const MOCK_RFQS: TradeRFQ[] = [
    {
        id: 'rfq-001',
        rfqNumber: 'RFQ-0042',
        title: 'Virgin Argan Oil — Cold Pressed, Cosmetic Grade',
        status: 'open',
        createdAt: '2026-02-28T10:00:00Z',
        expiresAt: '2026-03-10T23:59:00Z',
        productName: 'Virgin Argan Oil',
        category: 'Argan Oil & Derivatives',
        detailedRequirements: 'Cold-pressed, unroasted cosmetic-grade argan oil. Must meet EU Cosmetic Regulation (EC) 1223/2009. Organic certification preferred. Packaged in dark glass bottles or food-grade bulk containers.',
        specifications: [
            { key: 'Grade', value: 'Cosmetic (Cold-Pressed)' },
            { key: 'Certification', value: 'USDA Organic / Ecocert' },
            { key: 'Packaging', value: 'Dark glass 100ml or bulk 20L' },
            { key: 'Free Fatty Acid', value: '< 0.8%' },
        ],
        quantity: 500,
        quantityUnit: 'liters',
        targetPricePerUnit: 45,
        targetCurrency: 'USD',
        destinationPort: 'Jebel Ali, Dubai',
        incoterm: 'CIF',
        requiredByDate: '2026-04-15',
        targetCategories: ['Argan Oil & Derivatives'],
        invitedSupplierIds: ['sup-001', 'sup-002', 'sup-003'],
        aiScore: 92,
        aiSuggestions: [
            'Consider requesting samples from top 3 bidders before final selection',
            'Current market price for cosmetic argan is $42-48/L — your target is competitive',
        ],
        viewCount: 24,
        quoteCount: 4,
        quotes: [
            {
                id: 'q-001',
                rfqId: 'rfq-001',
                supplierId: 'sup-001',
                supplierName: 'Sahara Gold Cooperative',
                supplierCity: 'Agadir',
                supplierVerification: 'gold',
                quoteNumber: 'QT-2026-0112',
                status: 'submitted',
                submittedAt: '2026-03-02T14:30:00Z',
                unitPrice: 42.50,
                currency: 'USD',
                totalPrice: 21250,
                priceValidUntil: '2026-03-20',
                moq: 200,
                leadTimeDays: 14,
                incoterm: 'CIF',
                shippingCost: 850,
                paymentTerms: '30% advance, 70% on B/L',
                sampleAvailable: true,
                samplePrice: 15,
                aiComparisonScore: 94,
                aiNotes: 'Best price-quality ratio. Gold verified supplier with 98% on-time delivery. Recommended.',
                supplierNotes: 'We can provide Ecocert and USDA Organic certificates. First shipment in 10 days.',
                isNegotiable: true,
            },
            {
                id: 'q-002',
                rfqId: 'rfq-001',
                supplierId: 'sup-002',
                supplierName: 'Atlas Provisions Group',
                supplierCity: 'Essaouira',
                supplierVerification: 'verified',
                quoteNumber: 'QT-2026-0113',
                status: 'submitted',
                submittedAt: '2026-03-03T09:15:00Z',
                unitPrice: 46.00,
                currency: 'USD',
                totalPrice: 23000,
                priceValidUntil: '2026-03-25',
                moq: 100,
                leadTimeDays: 10,
                incoterm: 'CIF',
                shippingCost: 920,
                paymentTerms: '50% advance, 50% on delivery',
                sampleAvailable: true,
                samplePrice: 12,
                aiComparisonScore: 87,
                aiNotes: 'Lower MOQ and faster lead time. Price slightly above market average.',
                supplierNotes: 'Includes Ecocert certification. We specialize in cosmetic-grade argan.',
                isNegotiable: true,
            },
            {
                id: 'q-003',
                rfqId: 'rfq-001',
                supplierId: 'sup-003',
                supplierName: 'Souss Valley Organics',
                supplierCity: 'Taroudant',
                supplierVerification: 'verified',
                quoteNumber: 'QT-2026-0114',
                status: 'submitted',
                submittedAt: '2026-03-04T16:45:00Z',
                unitPrice: 44.00,
                currency: 'USD',
                totalPrice: 22000,
                priceValidUntil: '2026-03-22',
                moq: 300,
                leadTimeDays: 18,
                incoterm: 'FOB',
                paymentTerms: '100% L/C at sight',
                sampleAvailable: true,
                samplePrice: 20,
                aiComparisonScore: 82,
                aiNotes: 'Competitive pricing but higher MOQ and longer lead time. FOB terms mean buyer covers shipping.',
                isNegotiable: false,
            },
            {
                id: 'q-004',
                rfqId: 'rfq-001',
                supplierId: 'sup-004',
                supplierName: 'Marrakech Naturals',
                supplierCity: 'Marrakech',
                supplierVerification: 'basic',
                quoteNumber: 'QT-2026-0115',
                status: 'submitted',
                submittedAt: '2026-03-05T11:20:00Z',
                unitPrice: 39.00,
                currency: 'USD',
                totalPrice: 19500,
                priceValidUntil: '2026-03-18',
                moq: 500,
                leadTimeDays: 21,
                incoterm: 'EXW',
                paymentTerms: '100% advance',
                sampleAvailable: false,
                aiComparisonScore: 65,
                aiNotes: 'Lowest price but basic verification only. No samples available. EXW terms and full advance payment increase buyer risk.',
                isNegotiable: false,
            },
        ],
    },
    {
        id: 'rfq-002',
        rfqNumber: 'RFQ-0043',
        title: 'Handcut Zellige Tiles — Traditional Fez Pattern',
        status: 'comparing',
        createdAt: '2026-02-20T08:00:00Z',
        expiresAt: '2026-03-05T23:59:00Z',
        productName: 'Handcut Zellige Tiles',
        category: 'Ceramics & Zellige',
        detailedRequirements: 'Traditional handcut zellige tiles, 5x5cm, natural glaze in white, sage green, and deep blue. Must be kiln-fired using traditional methods.',
        specifications: [
            { key: 'Size', value: '5cm × 5cm (±2mm)' },
            { key: 'Colors', value: 'White, Sage Green, Deep Blue' },
            { key: 'Method', value: 'Traditional handcut, kiln-fired' },
        ],
        quantity: 5000,
        quantityUnit: 'pieces',
        targetPricePerUnit: 2.80,
        targetCurrency: 'USD',
        destinationPort: 'Jebel Ali, Dubai',
        incoterm: 'DAP',
        targetCategories: ['Ceramics & Zellige'],
        aiScore: 88,
        viewCount: 18,
        quoteCount: 3,
        quotes: [
            {
                id: 'q-005',
                rfqId: 'rfq-002',
                supplierId: 'sup-005',
                supplierName: 'Fez Artisan Zellige Co.',
                supplierCity: 'Fes',
                supplierVerification: 'gold',
                quoteNumber: 'QT-2026-0120',
                status: 'shortlisted',
                submittedAt: '2026-02-25T10:00:00Z',
                unitPrice: 2.60,
                currency: 'USD',
                totalPrice: 13000,
                priceValidUntil: '2026-03-15',
                moq: 1000,
                leadTimeDays: 28,
                incoterm: 'DAP',
                shippingCost: 1200,
                paymentTerms: '30% advance, 70% before shipping',
                sampleAvailable: true,
                samplePrice: 25,
                aiComparisonScore: 96,
                aiNotes: 'Premium artisan quality. Below target price. Gold verified with excellent track record.',
                isNegotiable: true,
            },
            {
                id: 'q-006',
                rfqId: 'rfq-002',
                supplierId: 'sup-006',
                supplierName: 'Meknes Ceramics Ltd',
                supplierCity: 'Meknes',
                supplierVerification: 'verified',
                quoteNumber: 'QT-2026-0121',
                status: 'submitted',
                submittedAt: '2026-02-26T15:30:00Z',
                unitPrice: 3.10,
                currency: 'USD',
                totalPrice: 15500,
                priceValidUntil: '2026-03-12',
                moq: 500,
                leadTimeDays: 21,
                incoterm: 'DAP',
                shippingCost: 1100,
                paymentTerms: '50/50',
                sampleAvailable: true,
                samplePrice: 30,
                aiComparisonScore: 78,
                aiNotes: 'Slightly above target but faster delivery and lower MOQ.',
                isNegotiable: true,
            },
            {
                id: 'q-007',
                rfqId: 'rfq-002',
                supplierId: 'sup-007',
                supplierName: 'Rabat Modern Tiles',
                supplierCity: 'Rabat',
                supplierVerification: 'basic',
                quoteNumber: 'QT-2026-0122',
                status: 'submitted',
                submittedAt: '2026-02-27T08:45:00Z',
                unitPrice: 2.20,
                currency: 'USD',
                totalPrice: 11000,
                priceValidUntil: '2026-03-10',
                moq: 3000,
                leadTimeDays: 35,
                incoterm: 'FOB',
                paymentTerms: '100% advance',
                sampleAvailable: false,
                aiComparisonScore: 58,
                aiNotes: 'Lowest price but semi-industrial process, not traditional handcut. Basic verification only.',
                isNegotiable: false,
            },
        ],
    },
    {
        id: 'rfq-003',
        rfqNumber: 'RFQ-0044',
        title: 'Premium Saffron Threads — Grade I (ISO 3632)',
        status: 'quoted',
        createdAt: '2026-03-01T12:00:00Z',
        expiresAt: '2026-03-15T23:59:00Z',
        productName: 'Saffron Threads',
        category: 'Saffron & Spices',
        detailedRequirements: 'Grade I saffron threads per ISO 3632. Crocin ≥ 200, safranal 20-50. Origin: Taliouine region preferred.',
        specifications: [
            { key: 'Grade', value: 'ISO 3632 Grade I' },
            { key: 'Crocin', value: '≥ 200' },
            { key: 'Origin', value: 'Taliouine, Morocco' },
        ],
        quantity: 10,
        quantityUnit: 'kg',
        targetPricePerUnit: 3500,
        targetCurrency: 'USD',
        destinationPort: 'Jebel Ali, Dubai',
        incoterm: 'CIF',
        targetCategories: ['Saffron & Spices'],
        aiScore: 85,
        viewCount: 31,
        quoteCount: 5,
        quotes: [],
    },
    {
        id: 'rfq-004',
        rfqNumber: 'RFQ-0045',
        title: 'Organic Extra Virgin Olive Oil — Bulk',
        status: 'draft',
        createdAt: '2026-03-07T16:00:00Z',
        expiresAt: '2026-03-25T23:59:00Z',
        productName: 'Extra Virgin Olive Oil',
        category: 'Olive Oil & Table Olives',
        detailedRequirements: 'Organic EVOO, acidity < 0.4%, cold extraction. Bulk 200L drums.',
        specifications: [
            { key: 'Type', value: 'Extra Virgin' },
            { key: 'Acidity', value: '< 0.4%' },
            { key: 'Packaging', value: '200L drums' },
        ],
        quantity: 2000,
        quantityUnit: 'liters',
        targetPricePerUnit: 8,
        targetCurrency: 'USD',
        destinationPort: 'Jebel Ali, Dubai',
        incoterm: 'CIF',
        targetCategories: ['Olive Oil & Table Olives'],
        viewCount: 0,
        quoteCount: 0,
        quotes: [],
    },
    {
        id: 'rfq-005',
        rfqNumber: 'RFQ-0041',
        title: 'Premium Leather Goods — Handcrafted Bags',
        status: 'awarded',
        createdAt: '2026-02-10T09:00:00Z',
        expiresAt: '2026-02-28T23:59:00Z',
        productName: 'Handcrafted Leather Bags',
        category: 'Textiles & Leather',
        detailedRequirements: 'Full-grain vegetable-tanned leather bags. Traditional Moroccan craftsmanship with modern design.',
        specifications: [
            { key: 'Material', value: 'Full-grain, vegetable-tanned' },
            { key: 'Styles', value: 'Tote, crossbody, weekender' },
        ],
        quantity: 200,
        quantityUnit: 'pieces',
        targetPricePerUnit: 45,
        targetCurrency: 'USD',
        destinationPort: 'Jebel Ali, Dubai',
        incoterm: 'DAP',
        targetCategories: ['Textiles & Leather'],
        aiScore: 90,
        viewCount: 42,
        quoteCount: 6,
        quotes: [],
        selectedQuoteId: 'q-awarded',
    },
];
