/**
 * Morocco Trade OS — Price Intelligence Mock Data
 */

import type { TradePriceData, TradePriceAlert } from '@/types/trade';

function generateHistory(basePrice: number, months: number, trend: 'rising' | 'stable' | 'falling'): { date: string; price: number }[] {
    const history: { date: string; price: number }[] = [];
    const trendFactor = trend === 'rising' ? 0.015 : trend === 'falling' ? -0.012 : 0;
    let price = basePrice * (1 - trendFactor * months);
    for (let i = months; i >= 0; i--) {
        const d = new Date(2026, 2 - i, 1);
        const noise = (Math.random() - 0.5) * basePrice * 0.04;
        price = price * (1 + trendFactor) + noise;
        history.push({
            date: d.toISOString().split('T')[0],
            price: Math.round(price * 100) / 100,
        });
    }
    return history;
}

export const MOCK_PRICES: TradePriceData[] = [
    {
        id: 'price-001',
        productName: 'Virgin Argan Oil (Cosmetic)',
        category: 'Argan Oil & Derivatives',
        currentPrice: 42.50,
        previousPrice: 46.00,
        currency: 'USD',
        unit: 'liter',
        trend: 'falling',
        changePercent: -7.6,
        benchmarks: { moroccoAvg: 44.00, globalAvg: 52.00, bestPrice: 39.00, bestPriceSupplier: 'Sahara Gold Cooperative' },
        history: generateHistory(44, 11, 'falling'),
        aiSummary: 'Argan oil prices declining due to strong 2025 harvest. Souss-Massa cooperatives are competing aggressively. Lock in contracts now before seasonal price recovery in Q4.',
    },
    {
        id: 'price-002',
        productName: 'Extra Virgin Olive Oil',
        category: 'Olive Oil & Table Olives',
        currentPrice: 8.20,
        previousPrice: 8.90,
        currency: 'USD',
        unit: 'liter',
        trend: 'falling',
        changePercent: -7.9,
        benchmarks: { moroccoAvg: 8.50, globalAvg: 11.20, bestPrice: 7.80, bestPriceSupplier: 'Meknes Olive Estates' },
        history: generateHistory(9, 11, 'falling'),
        aiSummary: 'Moroccan EVOO prices are significantly below the global average, driven by a bumper olive harvest in Fes-Meknes. European prices remain elevated due to drought.',
    },
    {
        id: 'price-003',
        productName: 'Saffron Threads (Grade I)',
        category: 'Saffron & Spices',
        currentPrice: 3800,
        previousPrice: 3600,
        currency: 'USD',
        unit: 'kg',
        trend: 'rising',
        changePercent: 5.6,
        benchmarks: { moroccoAvg: 3700, globalAvg: 4200, bestPrice: 3500, bestPriceSupplier: 'Taliouine Saffron Estate' },
        history: generateHistory(3600, 11, 'rising'),
        aiSummary: 'Saffron prices rising steadily due to increased demand from Gulf hospitality sector. Taliouine region output stable but pre-orders for 2026 harvest are already 40% filled.',
    },
    {
        id: 'price-004',
        productName: 'Handcut Zellige Tiles (5cm)',
        category: 'Ceramics & Zellige',
        currentPrice: 2.60,
        previousPrice: 2.50,
        currency: 'USD',
        unit: 'piece',
        trend: 'rising',
        changePercent: 4.0,
        benchmarks: { moroccoAvg: 2.80, globalAvg: 4.50, bestPrice: 2.20 },
        history: generateHistory(2.5, 11, 'rising'),
        aiSummary: 'Zellige prices rising with growing demand from Dubai luxury hospitality sector. Labor costs in Fez medina increasing. Traditional artisans becoming scarcer.',
    },
    {
        id: 'price-005',
        productName: 'Full-Grain Leather (Vegetable-Tanned)',
        category: 'Textiles & Leather',
        currentPrice: 18.50,
        previousPrice: 18.00,
        currency: 'USD',
        unit: 'sq ft',
        trend: 'stable',
        changePercent: 2.8,
        benchmarks: { moroccoAvg: 19.00, globalAvg: 24.00, bestPrice: 16.50, bestPriceSupplier: 'Casablanca Leather Works' },
        history: generateHistory(18, 11, 'stable'),
    },
    {
        id: 'price-006',
        productName: 'Ras el Hanout Spice Blend',
        category: 'Saffron & Spices',
        currentPrice: 12.00,
        previousPrice: 11.50,
        currency: 'USD',
        unit: 'kg',
        trend: 'rising',
        changePercent: 4.3,
        benchmarks: { moroccoAvg: 13.00, globalAvg: 18.00, bestPrice: 10.50 },
        history: generateHistory(11.5, 11, 'rising'),
    },
    {
        id: 'price-007',
        productName: 'Orange Blossom Water',
        category: 'Cosmetics & Beauty',
        currentPrice: 6.80,
        previousPrice: 7.00,
        currency: 'USD',
        unit: 'liter',
        trend: 'falling',
        changePercent: -2.9,
        benchmarks: { moroccoAvg: 7.20, globalAvg: 9.50, bestPrice: 6.00 },
        history: generateHistory(7, 11, 'falling'),
    },
    {
        id: 'price-008',
        productName: 'Preserved Lemons',
        category: 'Preserved Foods',
        currentPrice: 4.50,
        previousPrice: 4.40,
        currency: 'USD',
        unit: 'kg',
        trend: 'stable',
        changePercent: 2.3,
        benchmarks: { moroccoAvg: 4.80, globalAvg: 6.20, bestPrice: 3.90 },
        history: generateHistory(4.4, 11, 'stable'),
    },
    {
        id: 'price-009',
        productName: 'Moroccan Mint Tea (Bulk)',
        category: 'Tea & Herbal Infusions',
        currentPrice: 8.50,
        previousPrice: 8.20,
        currency: 'USD',
        unit: 'kg',
        trend: 'rising',
        changePercent: 3.7,
        benchmarks: { moroccoAvg: 9.00, globalAvg: 12.00, bestPrice: 7.80 },
        history: generateHistory(8.2, 11, 'rising'),
    },
    {
        id: 'price-010',
        productName: 'Prickly Pear Seed Oil',
        category: 'Cosmetics & Beauty',
        currentPrice: 320,
        previousPrice: 340,
        currency: 'USD',
        unit: 'liter',
        trend: 'falling',
        changePercent: -5.9,
        benchmarks: { moroccoAvg: 330, globalAvg: 400, bestPrice: 290 },
        history: generateHistory(340, 11, 'falling'),
        aiSummary: 'Prickly pear seed oil prices declining as more cooperatives enter the market. Quality remains the key differentiator — insist on cold-pressed, single-origin.',
    },
    {
        id: 'price-011',
        productName: 'Table Olives (Green)',
        category: 'Olive Oil & Table Olives',
        currentPrice: 2.80,
        previousPrice: 2.90,
        currency: 'USD',
        unit: 'kg',
        trend: 'falling',
        changePercent: -3.4,
        benchmarks: { moroccoAvg: 3.00, globalAvg: 4.20, bestPrice: 2.50 },
        history: generateHistory(2.9, 11, 'falling'),
    },
    {
        id: 'price-012',
        productName: 'Couscous (Hand-Rolled)',
        category: 'Couscous & Grains',
        currentPrice: 3.20,
        previousPrice: 3.10,
        currency: 'USD',
        unit: 'kg',
        trend: 'stable',
        changePercent: 3.2,
        benchmarks: { moroccoAvg: 3.50, globalAvg: 5.00, bestPrice: 2.80 },
        history: generateHistory(3.1, 11, 'stable'),
    },
];

export const MOCK_PRICE_ALERTS: TradePriceAlert[] = [
    {
        id: 'pa-1',
        productName: 'Extra Virgin Olive Oil',
        condition: 'below',
        threshold: 9.00,
        currency: 'USD',
        isActive: true,
        triggeredAt: '2026-03-06T22:10:00Z',
    },
    {
        id: 'pa-2',
        productName: 'Saffron Threads (Grade I)',
        condition: 'above',
        threshold: 4000,
        currency: 'USD',
        isActive: true,
    },
    {
        id: 'pa-3',
        productName: 'Virgin Argan Oil (Cosmetic)',
        condition: 'below',
        threshold: 40,
        currency: 'USD',
        isActive: true,
    },
];
