/**
 * Morocco Trade OS — Supplier Mock Data
 */

import type { TradeSupplier } from '@/types/trade';

export const MOCK_SUPPLIERS: TradeSupplier[] = [
    {
        id: 'sup-001',
        companyName: 'Sahara Gold Cooperative',
        slug: 'sahara-gold-cooperative',
        companyType: 'cooperative',
        region: 'Souss-Massa',
        city: 'Agadir',
        yearEstablished: 2008,
        employeeCount: '50-100',
        mainCategories: ['Argan Oil & Derivatives', 'Cosmetics & Beauty'],
        certifications: [
            { id: 'cert-1', name: 'USDA Organic', issuer: 'USDA', status: 'verified', expiresAt: '2027-06-15', verifiedAt: '2025-06-15' },
            { id: 'cert-2', name: 'Ecocert', issuer: 'Ecocert SA', status: 'verified', expiresAt: '2027-03-20' },
            { id: 'cert-3', name: 'Fair Trade', issuer: 'FLO', status: 'verified' },
        ],
        exportCountries: ['UAE', 'France', 'USA', 'Japan', 'UK'],
        hasExportLicense: true,
        freeZoneCertified: true,
        verificationLevel: 'gold',
        responseRate: 98,
        responseTimeHours: 4,
        onTimeDeliveryRate: 97,
        ratingAvg: 4.9,
        ratingCount: 127,
        totalTransactions: 342,
        repeatBuyerRate: 89,
        monthlyCapacity: '5,000 liters',
        moqMin: 100,
        moqCurrency: 'USD',
        leadTimeDaysMin: 7,
        leadTimeDaysMax: 14,
        sampleAvailable: true,
        aiMatchScore: 96,
        aiMatchReasons: ['Top argan oil producer in Souss-Massa', 'All required certifications', 'Excellent delivery record'],
        complianceScore: 94,
        languages: ['Arabic', 'French', 'English'],
        contactName: 'Fatima El Amrani',
        contactTitle: 'Export Director',
        description: 'Women-led cooperative producing premium cold-pressed argan oil since 2008. Vertically integrated from tree to bottle. USDA Organic and Ecocert certified.',
    },
    {
        id: 'sup-002',
        companyName: 'Atlas Provisions Group',
        slug: 'atlas-provisions-group',
        companyType: 'trading_company',
        region: 'Marrakech-Safi',
        city: 'Essaouira',
        yearEstablished: 2012,
        employeeCount: '25-50',
        mainCategories: ['Argan Oil & Derivatives', 'Olive Oil & Table Olives', 'Preserved Foods'],
        certifications: [
            { id: 'cert-4', name: 'ISO 22000', issuer: 'SGS', status: 'verified', expiresAt: '2027-01-10' },
            { id: 'cert-5', name: 'ONSSA Export License', issuer: 'ONSSA', status: 'verified' },
        ],
        exportCountries: ['UAE', 'Saudi Arabia', 'Qatar', 'Germany'],
        hasExportLicense: true,
        freeZoneCertified: false,
        verificationLevel: 'verified',
        responseRate: 92,
        responseTimeHours: 8,
        onTimeDeliveryRate: 91,
        ratingAvg: 4.6,
        ratingCount: 84,
        totalTransactions: 198,
        repeatBuyerRate: 76,
        monthlyCapacity: '3,000 liters',
        moqMin: 50,
        moqCurrency: 'USD',
        leadTimeDaysMin: 7,
        leadTimeDaysMax: 12,
        sampleAvailable: true,
        aiMatchScore: 88,
        aiMatchReasons: ['Multi-product portfolio', 'Strong Gulf market experience', 'ISO certified'],
        complianceScore: 82,
        languages: ['Arabic', 'French', 'English'],
        contactName: 'Youssef Bennani',
        contactTitle: 'Commercial Manager',
        description: 'Multi-category Moroccan provisions trading company specializing in premium food exports to the Gulf region. ISO 22000 certified facility in Essaouira.',
    },
    {
        id: 'sup-003',
        companyName: 'Souss Valley Organics',
        slug: 'souss-valley-organics',
        companyType: 'manufacturer',
        region: 'Souss-Massa',
        city: 'Taroudant',
        yearEstablished: 2015,
        employeeCount: '25-50',
        mainCategories: ['Argan Oil & Derivatives'],
        certifications: [
            { id: 'cert-6', name: 'Ecocert', issuer: 'Ecocert SA', status: 'verified' },
        ],
        exportCountries: ['UAE', 'France', 'Belgium'],
        hasExportLicense: true,
        freeZoneCertified: false,
        verificationLevel: 'verified',
        responseRate: 85,
        responseTimeHours: 12,
        onTimeDeliveryRate: 88,
        ratingAvg: 4.4,
        ratingCount: 52,
        totalTransactions: 97,
        repeatBuyerRate: 71,
        monthlyCapacity: '2,000 liters',
        moqMin: 200,
        moqCurrency: 'USD',
        leadTimeDaysMin: 14,
        leadTimeDaysMax: 21,
        sampleAvailable: true,
        aiMatchScore: 79,
        complianceScore: 75,
        languages: ['Arabic', 'French'],
        contactName: 'Hassan Ouarzazate',
        contactTitle: 'General Manager',
        description: 'Family-owned argan oil production facility in the heart of Souss Valley. Organic certification and direct relationships with local cooperatives.',
    },
    {
        id: 'sup-005',
        companyName: 'Fez Artisan Zellige Co.',
        slug: 'fez-artisan-zellige',
        companyType: 'artisan',
        region: 'Fes-Meknes',
        city: 'Fes',
        yearEstablished: 1985,
        employeeCount: '100-200',
        mainCategories: ['Ceramics & Zellige'],
        certifications: [
            { id: 'cert-7', name: 'Moroccan Artisan Mark', issuer: 'Ministry of Handicrafts', status: 'verified' },
            { id: 'cert-8', name: 'UNESCO Heritage Partner', issuer: 'UNESCO', status: 'verified' },
        ],
        exportCountries: ['UAE', 'USA', 'UK', 'France', 'Italy', 'Spain'],
        hasExportLicense: true,
        freeZoneCertified: false,
        verificationLevel: 'gold',
        responseRate: 95,
        responseTimeHours: 6,
        onTimeDeliveryRate: 93,
        ratingAvg: 4.8,
        ratingCount: 203,
        totalTransactions: 456,
        repeatBuyerRate: 88,
        monthlyCapacity: '50,000 pieces',
        moqMin: 500,
        moqCurrency: 'USD',
        leadTimeDaysMin: 21,
        leadTimeDaysMax: 35,
        sampleAvailable: true,
        aiMatchScore: 94,
        aiMatchReasons: ['40+ years of zellige mastery', 'UNESCO heritage partner', 'Global export experience'],
        complianceScore: 91,
        languages: ['Arabic', 'French', 'English', 'Spanish'],
        contactName: 'Moulay Ahmed Fassi',
        contactTitle: 'Master Artisan & CEO',
        description: 'Fourth-generation zellige tile atelier in the Fez medina. Handcut zellige using centuries-old techniques. UNESCO Heritage Partner. Exported to luxury hotels worldwide.',
    },
    {
        id: 'sup-006',
        companyName: 'Casablanca Leather Works',
        slug: 'casablanca-leather-works',
        companyType: 'manufacturer',
        region: 'Casablanca-Settat',
        city: 'Casablanca',
        yearEstablished: 2001,
        employeeCount: '200-500',
        mainCategories: ['Textiles & Leather'],
        certifications: [
            { id: 'cert-9', name: 'ISO 9001', issuer: 'Bureau Veritas', status: 'verified' },
            { id: 'cert-10', name: 'LWG Certified', issuer: 'Leather Working Group', status: 'verified' },
        ],
        exportCountries: ['UAE', 'Saudi Arabia', 'USA', 'UK', 'Germany'],
        hasExportLicense: true,
        freeZoneCertified: true,
        verificationLevel: 'gold',
        responseRate: 97,
        responseTimeHours: 3,
        onTimeDeliveryRate: 95,
        ratingAvg: 4.7,
        ratingCount: 312,
        totalTransactions: 678,
        repeatBuyerRate: 91,
        monthlyCapacity: '10,000 pieces',
        moqMin: 100,
        moqCurrency: 'USD',
        leadTimeDaysMin: 14,
        leadTimeDaysMax: 28,
        sampleAvailable: true,
        aiMatchScore: 91,
        aiMatchReasons: ['Large-scale production capacity', 'LWG sustainability certification', 'Free zone certified'],
        complianceScore: 93,
        languages: ['Arabic', 'French', 'English'],
        contactName: 'Karim Tazi',
        contactTitle: 'VP International Sales',
        description: 'One of Morocco\'s leading leather goods manufacturers. Full-grain vegetable-tanned leather products. LWG and ISO 9001 certified. Free zone operations for duty-free export.',
    },
    {
        id: 'sup-007',
        companyName: 'Taliouine Saffron Estate',
        slug: 'taliouine-saffron-estate',
        companyType: 'cooperative',
        region: 'Souss-Massa',
        city: 'Taliouine',
        yearEstablished: 1998,
        employeeCount: '50-100',
        mainCategories: ['Saffron & Spices'],
        certifications: [
            { id: 'cert-11', name: 'ISO 3632 Grade I', issuer: 'ISO', status: 'verified' },
            { id: 'cert-12', name: 'Geographic Indication', issuer: 'OMPIC', status: 'verified' },
        ],
        exportCountries: ['UAE', 'Spain', 'Italy', 'France'],
        hasExportLicense: true,
        freeZoneCertified: false,
        verificationLevel: 'gold',
        responseRate: 90,
        responseTimeHours: 8,
        onTimeDeliveryRate: 94,
        ratingAvg: 4.9,
        ratingCount: 89,
        totalTransactions: 167,
        repeatBuyerRate: 85,
        monthlyCapacity: '50 kg',
        moqMin: 1,
        moqCurrency: 'USD',
        leadTimeDaysMin: 10,
        leadTimeDaysMax: 18,
        sampleAvailable: true,
        aiMatchScore: 93,
        aiMatchReasons: ['Geographic Indication certified', 'ISO 3632 Grade I saffron', 'Premier Taliouine terroir'],
        complianceScore: 89,
        languages: ['Arabic', 'French'],
        contactName: 'Aicha Saffrani',
        contactTitle: 'Cooperative President',
        description: 'Premier saffron producer in Taliouine — Morocco\'s saffron capital. ISO 3632 Grade I certified. Protected Geographic Indication. Hand-harvested at peak bloom.',
    },
    {
        id: 'sup-008',
        companyName: 'Meknes Olive Estates',
        slug: 'meknes-olive-estates',
        companyType: 'manufacturer',
        region: 'Fes-Meknes',
        city: 'Meknes',
        yearEstablished: 2005,
        employeeCount: '100-200',
        mainCategories: ['Olive Oil & Table Olives'],
        certifications: [
            { id: 'cert-13', name: 'Organic EU', issuer: 'Ecocert', status: 'verified' },
            { id: 'cert-14', name: 'HACCP', issuer: 'SGS', status: 'verified' },
        ],
        exportCountries: ['UAE', 'USA', 'Canada', 'France', 'UK'],
        hasExportLicense: true,
        freeZoneCertified: true,
        verificationLevel: 'verified',
        responseRate: 94,
        responseTimeHours: 5,
        onTimeDeliveryRate: 92,
        ratingAvg: 4.6,
        ratingCount: 156,
        totalTransactions: 289,
        repeatBuyerRate: 82,
        monthlyCapacity: '20,000 liters',
        moqMin: 500,
        moqCurrency: 'USD',
        leadTimeDaysMin: 10,
        leadTimeDaysMax: 20,
        sampleAvailable: true,
        aiMatchScore: 87,
        aiMatchReasons: ['High-volume olive oil producer', 'EU Organic and HACCP certified', 'Free zone operations'],
        complianceScore: 86,
        languages: ['Arabic', 'French', 'English'],
        contactName: 'Omar El Fassi',
        contactTitle: 'Export Director',
        description: 'Large-scale organic olive oil producer in the fertile Meknes-Saiss plain. Cold extraction facility. EU Organic and HACCP certified. Bulk and retail packaging.',
    },
    {
        id: 'sup-009',
        companyName: 'Marrakech Artisan Textiles',
        slug: 'marrakech-artisan-textiles',
        companyType: 'artisan',
        region: 'Marrakech-Safi',
        city: 'Marrakech',
        yearEstablished: 1992,
        employeeCount: '25-50',
        mainCategories: ['Textiles & Leather'],
        certifications: [
            { id: 'cert-15', name: 'Moroccan Artisan Mark', issuer: 'Ministry of Handicrafts', status: 'verified' },
        ],
        exportCountries: ['UAE', 'UK', 'USA'],
        hasExportLicense: true,
        freeZoneCertified: false,
        verificationLevel: 'verified',
        responseRate: 88,
        responseTimeHours: 10,
        onTimeDeliveryRate: 86,
        ratingAvg: 4.5,
        ratingCount: 67,
        totalTransactions: 134,
        repeatBuyerRate: 74,
        monthlyCapacity: '500 pieces',
        moqMin: 20,
        moqCurrency: 'USD',
        leadTimeDaysMin: 14,
        leadTimeDaysMax: 30,
        sampleAvailable: true,
        aiMatchScore: 76,
        complianceScore: 72,
        languages: ['Arabic', 'French', 'English'],
        contactName: 'Nadia Rachidi',
        contactTitle: 'Creative Director',
        description: 'Handwoven Moroccan textiles including caftans, throws, and home décor. Traditional weaving techniques with contemporary design. Each piece is unique.',
    },
];
